name: Release
permissions:
  contents: read
  packages: write
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    uses: Lua-cat/ci-templates/.github/workflows/nuget-minver.yml@main
    secrets: inherit
